require 'rake'

task :default do
  #sh 'make clean'
  sh 'make'
  puts "=====================================\n"
  sh './indexer foo sample'
end

task :mem do
  sh 'make'
  sh 'valgrind ./indexer foo sample'
end

task :clean do
  sh 'make clean'
end

task :big do
  sh 'make'
  puts "=====================================\n"
  sh './indexer foo aiser'
end
  
task :io do
  sh 'make'
  sh './indexer exists sample'
end
